/**
 * Descripción de cada producto (clave = nombre de la familia en families.ts).
 * Texto general del tipo de producto, sin datos técnicos inventados (rendimiento,
 * tiempos de secado, etc.): para eso, consultar la ficha del fabricante.
 * Se pueden editar desde el admin (campo "Descripción") sin tocar este archivo.
 */
export const DESCRIPTIONS: Record<string, string> = {
  // ---- Látex y pinturas de pared ----
  'Albacryl Látex Interior Mate': 'Látex mate para paredes y cielorrasos interiores, con acabado uniforme y propiedades antihongo. Ideal para renovar living, dormitorios y ambientes de uso diario.',
  'Albalatex Látex Interior': 'Línea de látex interior de Alba en distintos acabados (mate, satinado y ultra lavable). Para pintar paredes y cielorrasos con un acabado prolijo y fácil de limpiar.',
  'Albalatex Design Colores': 'Látex interior de Alba en una amplia gama de colores de tendencia. Elegí el tono en la ficha y combiná ambientes con color.',
  'Albafrent Frentes y Muros': 'Látex acrílico para exteriores: frentes, muros y medianeras. Protege la pared de la intemperie y deja un acabado mate parejo.',
  'Albaxpert Látex Mate': 'Látex mate de la línea Albaxpert de Alba para interiores. Una opción práctica para pintar grandes superficies.',
  'Centro Mate Superior Antihongo': 'Látex mate de nuestra marca para interiores, con protección antihongo. Para pintar paredes y cielorrasos.',
  'Centro Profesional Látex Ext/Int': 'Látex profesional de nuestra marca, apto para interior y exterior. Pensado para el pintor que necesita buen rendimiento en obra.',
  'Cielos Rasos Standard': 'Pintura látex blanca para cielorrasos. Cubre bien y deja un acabado mate uniforme que disimula imperfecciones.',
  'Constructor Látex Int/Ext': 'Látex mate de Alba para paredes interiores y exteriores. Disponible en blanco y en varios colores.',
  'Duralba Látex Acrílico Exterior': 'Látex acrílico de Alba para exteriores en varios colores. Resiste la intemperie y mantiene el color en frentes y muros.',
  'Duralba Frentes y Muros': 'Pintura impermeabilizante de Alba para frentes y muros exteriores. Ayuda a proteger la pared de la humedad y la lluvia.',
  'Pintura para Piletas': 'Pintura de Alba para piletas de natación de hormigón o revoque. Se aplica sobre superficies preparadas y deja un acabado celeste.',
  'Pisos Látex Acrílico': 'Pintura látex acrílica de Alba para pisos: patios, garajes, veredas y contrapisos. Elegí el color en la ficha.',
  'Look Látex Frentes y Tendencias': 'Látex de la línea Look de Emapi para frentes y ambientes, en colores clásicos y de tendencia.',
  // ---- Esmaltes ----
  'Albalux Diam 3 en 1': 'Esmalte sintético de Alba con tres funciones en uno: antióxido, convertidor y esmalte. Para proteger y decorar metales y maderas, en una gran variedad de colores.',
  'Albalux 2 en 1 Forja y Martillado': 'Esmalte sintético de Alba que combina protección antióxido y terminación. Disponible en acabados forja y martillado para rejas, portones y herrería.',
  'Albalux Balance Esmalte al Agua': 'Esmalte al agua de Alba, de bajo olor y fácil limpieza de herramientas. Para madera y metal en interiores.',
  'Satinol Esmalte Satinado': 'Esmalte sintético satinado de Alba para madera y metal. Deja un acabado suave y resistente.',
  'Albamate Esmalte Sintético Mate': 'Esmalte sintético mate de Alba para madera y metal, con terminación sin brillo.',
  'Cromática Esmalte Sintético': 'Esmalte sintético de Emapi para madera y metal en brillante, satinado y mate. Disponible en varios colores.',
  'Pizarrones': 'Pintura de Alba para crear superficies de pizarrón en pared o madera. Ideal para escuelas, comercios y habitaciones de chicos.',
  // ---- Antióxidos ----
  'Antióxido Standard': 'Fondo antióxido de Alba para proteger hierro y acero antes de pintar con esmalte. Previene la formación de óxido.',
  'CM Antióxido': 'Antióxido de Emapi para proteger superficies metálicas antes del esmalte. Disponible en blanco, negro y rojo.',
  'Convertidor de Óxido Alba': 'Transforma el óxido superficial en una capa estable sobre la que se puede pintar. Para rejas, portones y estructuras de hierro.',
  'CM Convertidor de Óxido': 'Convertidor de óxido de Emapi: detiene el óxido y deja la base lista para el esmalte. Varios colores.',
  // ---- Preparación de superficies ----
  'Centro Enduido + Masilla': 'Enduido plástico de nuestra marca para rellenar grietas y nivelar paredes interiores antes de pintar.',
  'Enduido + Masilla': 'Enduido de Alba para reparar y nivelar paredes interiores. Se lija fácilmente y deja la superficie lista para pintar.',
  'Enduido Exterior Premium': 'Enduido de Alba para reparar frentes y paredes exteriores antes de pintar.',
  'Centro Fijador al Agua': 'Fijador al agua de nuestra marca. Se aplica antes de la pintura para sellar la superficie y mejorar la adherencia.',
  'Fijador al Aguarrás': 'Fijador de Alba a base de solvente para consolidar paredes y mejorar la adherencia de la pintura. Disponible en Premium y Standard.',
  'Fondo Blanco Premium': 'Fondo blanco de Alba para preparar madera y metal antes del esmalte. Mejora la cobertura y el acabado final.',
  'Fondo Universal al Agua': 'Fondo al agua de Alba para distintos tipos de superficie. Sin olor fuerte y fácil de aplicar.',
  'Alabastine Repara Paredes': 'Masilla de Alabastine (Alba) lista para usar, para reparar agujeros, golpes y fisuras en paredes interiores.',
  'Masilla Poliéster': 'Masilla poliéster de Sinteplast de dos componentes para reparar y nivelar superficies. Se lija una vez curada.',
  'Masilla Piroxilina Roja': 'Masilla universal de Sinteplast para correcciones menores y retoques de superficie.',
  // ---- Impermeabilizantes y revestimientos ----
  'Liquitech Cauchogoma Impermeabilizante': 'Impermeabilizante de Merclin (línea Liquitech) tipo caucho-goma, para techos y terrazas. Forma una capa flexible que protege de las filtraciones.',
  'Liquitech Membrana Poliuretánica en Pasta': 'Membrana poliuretánica en pasta de Merclin (Liquitech) para impermeabilizar techos y superficies expuestas.',
  'Liquitech Tapa Goteras': 'Producto de Merclin (Liquitech) para sellar goteras y fisuras en techos de forma rápida.',
  'Liquitech Membrana Autoadhesiva': 'Membrana autoadhesiva de Merclin (Liquitech) en rollo para sellar juntas, uniones y reparaciones puntuales.',
  'Liquitech Impermeabilizante para Ladrillo': 'Tratamiento de Merclin (Liquitech) para ladrillos a la vista: protege de la humedad y realza el color. Natural o rojo.',
  'Impermeabilizante M y M': 'Impermeabilizante para muros y medianeras de Distinción, en distintos colores. Protege la pared de la humedad.',
  'Texturado Marmolato': 'Revestimiento texturado de Venezia para dar terminación decorativa a frentes e interiores. Disponible en distintos granos y colores.',
  // ---- Maderas ----
  'Albatros Barniz Marino': 'Barniz marino de Alba para madera expuesta al exterior. Protege de la humedad y del sol y deja un acabado brillante.',
  'Cetol Classic Brillante': 'Protector de madera de Cetol con acabado brillante. Resalta la veta y protege aberturas, muebles y deck. Elegí el tono en la ficha.',
  'Cetol Classic Satinado': 'Protector de madera de Cetol con acabado satinado. Realza la veta y cuida la madera. Elegí el tono en la ficha.',
  'Cetol Tinta Universal': 'Tintas universales de Cetol para dar color a la madera sin tapar la veta. Varios tonos.',
  'Cetol Deck': 'Protector de Cetol pensado para decks y maderas de exterior sometidas a sol y lluvia.',
  'Pro Madera Barniz': 'Barniz de Emapi para madera en acabados brillante, mate y satinado. Protege y realza la veta.',
  'Pro Madera Tratamiento Protector': 'Tratamiento protector de Emapi para madera, con color y acabado satinado o tradicional.',
  'Brikol Pisos': 'Pintura de Cetol (Brikol) para pisos. Protege y renueva el color en distintos tonos.',
  'Aceite de Lino': 'Aceite de lino de Geo para tratar y proteger madera. También se usa para diluir y preparar ciertas pinturas.',
  // ---- Solventes ----
  'Aguarrás': 'Aguarrás de Geo para diluir esmaltes sintéticos y barnices, y para limpiar pinceles y herramientas.',
  'Thinner Sello Oro': 'Diluyente thinner de Dixilina para pinturas y lacas, y para limpieza de herramientas y equipos.',
  'Removedor en Gel': 'Removedor en gel de Dixilina para quitar pintura y barniz de madera y metal.',
  // ---- Aerosoles ----
  'Aerosol Toke': 'Pintura en aerosol de Toke de secado rápido, en acabados mate, satinado y brillante. También hay versiones para alta temperatura y llantas. Elegí el color en la ficha.',
  'Aerosol Colorgin': 'Pintura en aerosol Colorgin para retoques y pequeños trabajos de decoración sobre metal, madera y plástico.',
  'Aerosol Ultra Cover 2X': 'Aerosol Ultra Cover 2X de Rust-Oleum, con alta cobertura para pintar y renovar objetos del hogar.',
  'Aerosol Línea Joven': 'Aerosoles de Distinción en colores jóvenes y pasteles, para manualidades y decoración.',
  'Aerosol Tekbond': 'Pintura en aerosol de Tekbond para trabajos rápidos de decoración y retoque. Varios colores.',
  // ---- Adhesivos y selladores ----
  'Silicona Acética Multiuso': 'Silicona acética de Fischer para sellar juntas en vidrio, cerámica, aluminio y sanitarios. Incolora.',
  'Sellador Neutro': 'Sellador de silicona neutra de Fischer, apto para más materiales que la silicona acética. Blanco, negro o transparente.',
  'Sella Canaletas': 'Sellador de Tekbond para canaletas, juntas y uniones exteriores. En aluminio o incoloro.',
  'Poximix Exterior': 'Masa epoxi de dos componentes para reparar grietas y rellenar en exteriores.',
  'Poximix Interior': 'Masa epoxi de dos componentes para reparaciones y fijaciones en interiores.',
  'Pistola Aplicadora para Silicona': 'Pistola de Rottweiler para aplicar siliconas y selladores en cartucho de forma pareja y con control.',
  'Kit Parche': 'Kit de Sinteplast con lo necesario para reparar pequeños agujeros y desperfectos en paredes.',
  // ---- Pinceles y rodillos ----
  'Pincel Gold': 'Pincel de El Galgo línea Gold, de buena terminación para esmaltes, barnices y látex. Elegí el número en la ficha.',
  'Pincel Persianero': 'Pincel de El Galgo en formato persianero, para pintar con precisión en rincones, ventanas y rejas. Varios números.',
  'Pincel Yago V1 Blanco': 'Pincel Yago de Rosarpin, versión V1 de cerda blanca, para uso general. Elegí el número en la ficha.',
  'Pincel Yago V2': 'Pincel Yago de Rosarpin, versión V2, de uso general para pintura al agua y sintéticos. Varios números.',
  'Pinceleta Obra': 'Pinceleta de El Galgo para pintar superficies grandes en obra con rapidez.',
  'Rodillo Antigota': 'Rodillo antigota de Rosarpin que reduce las salpicaduras al pintar paredes y cielorrasos.',
  'Rodillo Cuero Lanar': 'Rodillo de lana de cuero de El Galgo para pintar con buena carga de pintura.',
  'Rodillo Foam': 'Rodillos de espuma de El Galgo para acabados lisos con esmaltes y barnices. Elegí el tamaño en la ficha.',
  'Rodillo Hilado Extremo': 'Rodillo de Rosarpin con hilado de alta carga, para paredes y cielorrasos.',
  'Rodillo Sintético Profesional': 'Rodillo sintético de Rosarpin para uso profesional, con buena absorción y terminación pareja.',
  'Rodillo Epoxi': 'Rodillos de Rosarpin aptos para pinturas epoxi y de dos componentes. Disponibles en versión estándar, alto sólido y mini.',
  'Bandeja para Pintor': 'Bandejas de Rosarpin para cargar el rodillo. Hay modelo plano, mini y para colgar de la escalera.',
  // ---- Cintas, cobertores y protección ----
  'Cinta de Enmascarar Azul Premium': 'Cinta de enmascarar azul premium de Sherwin-Williams para delimitar y proteger al pintar. Se retira sin dejar residuos.',
  'Cinta de Enmascarar Automotor': 'Cintas de enmascarar de Sherwin-Williams para pintura automotor, en distintos anchos.',
  'Cobertor Plástico': 'Cobertor de plástico de Rosarpin para proteger pisos, muebles y aberturas de salpicaduras al pintar.',
  'Film Plástico para Enmascarar': 'Film plástico de Sherwin-Williams para enmascarar superficies amplias junto con cinta de papel.',
  // ---- Lijas y abrasivos ----
  'Lija Azul Norton al Agua': 'Lija azul al agua de Norton, para lijar pintura, masilla y madera en seco o húmedo. Elegí el grano en la ficha: los números bajos son más gruesos y los altos más finos.',
  'Lija al Agua Norton T277': 'Lija al agua Norton T277 para lijado fino de pintura y terminaciones. Elegí el grano en la ficha.',
  'Lija al Agua El Galgo': 'Lija al agua de El Galgo para lijar pintura, masilla y metal. Elegí el grano en la ficha.',
  'Lija Disco Norton A275': 'Discos de lija Norton A275 para lijadora orbital. Elegí el grano en la ficha.',
  'Hoja Tela Esmeril Norton': 'Hojas de tela esmeril Norton para lijar metal y madera, resistentes y flexibles. Elegí el grano en la ficha.',
  'Lija Tela Esmeril 3M': 'Lija de tela esmeril 3M para trabajos en metal y madera. Elegí el grano en la ficha.',
  'Lija Sinteplast': 'Lijas de Sinteplast en granos finos para preparar y pulir superficies antes de pintar.',
  'Disco Flap Óxido de Aluminio': 'Disco flap de óxido de aluminio de Rottweiler para amoladora, ideal para lijar y desbastar metal. Elegí el grano en la ficha.',
  // ---- Herramientas ----
  'Espátula de Acero': 'Espátulas de acero de Mota para masillar, raspar y retirar pintura. Elegí el ancho en la ficha.',
  'Llana Plástica de Alto Impacto': 'Llana plástica de alto impacto de 12 x 30 cm para alisar enduido y masillas.',
  'Guantes de Trabajo': 'Guantes de Fueguino para trabajos de pintura, limpieza y obra. Modelos liviano y moteado.',
  'Viruta de Acero': 'Viruta de acero de Apeles para lijar y pulir madera y metal. Fina, mediana y gruesa.',
  'Estopa Lustre': 'Estopa de Apeles de 350 gr para limpiar, lustrar y aplicar ceras y tratamientos.',
  'Trapo': 'Trapo Cavalieri de 500 gr para limpieza y terminación en trabajos de pintura.',
  'Cepillo de Alambre': 'Cepillo de alambre de bronce de Fueguino con mango, para limpiar óxido y pintura suelta.',
  'Raspador de Pintura y Calco': 'Raspador de Fueguino para retirar pintura vieja, calcomanías y restos de superficies.',
  'Cutter Metálico': 'Cutter metálico de Rottweiler para cortes precisos en cintas, cartón y papel.',
  'Anteojo de Policarbonato': 'Anteojo de seguridad de Fueguino, de policarbonato transparente, para proteger los ojos al lijar, pintar o cortar.',
};
